sudo: false

language: go
go:
  - 1.4
  - 1.5

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/mattn/goveralls
  - go get github.com/mitchellh/gox

install:
  - go get -t -v ./...
  - make updatedeps

script:
  - make format
  - make lint
  - make vet
